export const columns = [
	{ title: 'Дата создания', key: 'date' },
	{ title: 'Оффер', key: 'offer' },
	{ title: 'Гео/IP', key: 'geo.name' },
	{ title: 'Устройство', key: 'device.os' },
	{ title: 'Статус', key: 'status' },
	{ title: 'Доход', key: 'income' },
	{ title: 'Название цели', key: 'goal' },
	{ title: 'sub1', key: 'sub1' },
	{ title: 'sub2', key: 'sub2' },
	{ title: 'sub3', key: 'sub3' },
	{ title: 'sub4', key: 'sub4' },
	{ title: 'sub5', key: 'sub5' },
	{ title: 'sub6', key: 'sub6' },
	{ title: 'sub7', key: 'sub7' },
	{ title: 'User Agent', key: 'user_agent' },
	{ title: 'комментарий', key: 'comment' },
	{ title: 'id', key: 'id' },
]
